site :opscode

cookbook 'yum'
cookbook 'yum-epel'
cookbook 'nginx'
cookbook 'mysql'
cookbook 'git'
cookbook 'nodejs', git:'https://github.com/mdxp/nodejs-cookbook.git'
cookbook 'rbenv-ruby', path: 'site-cookbooks/rbenv-ruby'
