require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AnswerFilesController do

  # This should return the minimal set of attributes required to create a valid
  # AnswerFile. As you add validations to AnswerFile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "answer" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnswerFilesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all answer_files as @answer_files" do
      answer_file = AnswerFile.create! valid_attributes
      get :index, {}, valid_session
      assigns(:answer_files).should eq([answer_file])
    end
  end

  describe "GET show" do
    it "assigns the requested answer_file as @answer_file" do
      answer_file = AnswerFile.create! valid_attributes
      get :show, {:id => answer_file.to_param}, valid_session
      assigns(:answer_file).should eq(answer_file)
    end
  end

  describe "GET new" do
    it "assigns a new answer_file as @answer_file" do
      get :new, {}, valid_session
      assigns(:answer_file).should be_a_new(AnswerFile)
    end
  end

  describe "GET edit" do
    it "assigns the requested answer_file as @answer_file" do
      answer_file = AnswerFile.create! valid_attributes
      get :edit, {:id => answer_file.to_param}, valid_session
      assigns(:answer_file).should eq(answer_file)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AnswerFile" do
        expect {
          post :create, {:answer_file => valid_attributes}, valid_session
        }.to change(AnswerFile, :count).by(1)
      end

      it "assigns a newly created answer_file as @answer_file" do
        post :create, {:answer_file => valid_attributes}, valid_session
        assigns(:answer_file).should be_a(AnswerFile)
        assigns(:answer_file).should be_persisted
      end

      it "redirects to the created answer_file" do
        post :create, {:answer_file => valid_attributes}, valid_session
        response.should redirect_to(AnswerFile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved answer_file as @answer_file" do
        # Trigger the behavior that occurs when invalid params are submitted
        AnswerFile.any_instance.stub(:save).and_return(false)
        post :create, {:answer_file => { "answer" => "invalid value" }}, valid_session
        assigns(:answer_file).should be_a_new(AnswerFile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AnswerFile.any_instance.stub(:save).and_return(false)
        post :create, {:answer_file => { "answer" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested answer_file" do
        answer_file = AnswerFile.create! valid_attributes
        # Assuming there are no other answer_files in the database, this
        # specifies that the AnswerFile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AnswerFile.any_instance.should_receive(:update).with({ "answer" => "" })
        put :update, {:id => answer_file.to_param, :answer_file => { "answer" => "" }}, valid_session
      end

      it "assigns the requested answer_file as @answer_file" do
        answer_file = AnswerFile.create! valid_attributes
        put :update, {:id => answer_file.to_param, :answer_file => valid_attributes}, valid_session
        assigns(:answer_file).should eq(answer_file)
      end

      it "redirects to the answer_file" do
        answer_file = AnswerFile.create! valid_attributes
        put :update, {:id => answer_file.to_param, :answer_file => valid_attributes}, valid_session
        response.should redirect_to(answer_file)
      end
    end

    describe "with invalid params" do
      it "assigns the answer_file as @answer_file" do
        answer_file = AnswerFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AnswerFile.any_instance.stub(:save).and_return(false)
        put :update, {:id => answer_file.to_param, :answer_file => { "answer" => "invalid value" }}, valid_session
        assigns(:answer_file).should eq(answer_file)
      end

      it "re-renders the 'edit' template" do
        answer_file = AnswerFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AnswerFile.any_instance.stub(:save).and_return(false)
        put :update, {:id => answer_file.to_param, :answer_file => { "answer" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested answer_file" do
      answer_file = AnswerFile.create! valid_attributes
      expect {
        delete :destroy, {:id => answer_file.to_param}, valid_session
      }.to change(AnswerFile, :count).by(-1)
    end

    it "redirects to the answer_files list" do
      answer_file = AnswerFile.create! valid_attributes
      delete :destroy, {:id => answer_file.to_param}, valid_session
      response.should redirect_to(answer_files_url)
    end
  end

end
